import { menuCategories } from "../menu-data"
import type { DatabaseShape } from "../types"

export function buildSeed(): DatabaseShape {
  return {
    settings: {
      name: "LUMINA",
      tagline: "Fine Dining Experience",
      heroSubtitle: "Where culinary artistry meets timeless elegance",
      chef: "Marcus Chen",
      cuisine: "Modern Fusion",
      hoursDays: "Tuesday - Sunday",
      hoursTime: "6:00 PM - 11:00 PM",
      address1: "123 Culinary Avenue",
      address2: "Manhattan, NY 10013",
      phone: "+1 (212) 555-0123",
      email: "reservations@lumina.com",
      instagram: "https://instagram.com/lumina",
      announcement: "Now taking reservations for our Midsummer Truffle Season",
      about: {
        story: [
          "Lumina was born in 2016 from a single conviction: that a dinner can be a work of art. Chef Marcus Chen left the three-star kitchens of Paris and Tokyo to build a room where light, sound and flavor move together.",
          "Every plate that leaves our kitchen is composed like a small stage — seasonal ingredients sourced from twenty-three trusted growers, fishermen and foragers, refined through classical French technique and a quietly Japanese sense of restraint.",
          "A decade later, the ritual is unchanged. The doors open at six. The candles are lit. And for one evening, time slows down.",
        ],
        vision:
          "To be remembered not as a restaurant, but as the most luminous evening of our guests' year — a house where hospitality is practiced as a fine art.",
        mission:
          "We craft transformative dining experiences by honoring exceptional ingredients, mastering our craft daily, and caring for every guest as if the entire evening were built for them alone.",
        values: [
          { title: "Craftsmanship", text: "Technique perfected over ten thousand quiet hours, visible in every cut, sauce and sear." },
          { title: "Provenance", text: "We know the name of every farm, boat and vineyard behind our ingredients." },
          { title: "Hospitality", text: "Anticipation over reaction — your glass is never empty, your pace is never rushed." },
          { title: "Wonder", text: "A meal should hold at least one moment you have never tasted before." },
        ],
        stats: [
          { label: "Years of excellence", value: "10" },
          { label: "Michelin stars", value: "2" },
          { label: "Signature dishes", value: "18" },
          { label: "Wine references", value: "600+" },
        ],
      },
      ordering: {
        enabled: true,
        minOrder: 40,
        pickupNote: "Orders are prepared à la minute. Please allow 35–45 minutes before pickup.",
      },
      reservationSlots: ["6:00 PM", "6:30 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM", "9:00 PM", "9:30 PM", "10:00 PM"],
    },
    categories: menuCategories.map((cat) => ({
      ...cat,
      items: cat.items.map((item) => ({ ...item, available: true })),
    })),
    experiences: [
      {
        id: "exp-couples",
        title: "Constellation for Two",
        subtitle: "Couples Tasting Combo",
        description:
          "A seven-course journey designed to be shared: two glasses of vintage champagne, our signature scallops and wagyu, and a chocolate sphere finished tableside under candlelight.",
        price: 320,
        priceLabel: "per couple",
        category: "couples",
        image: "/images/champagne.jpg",
        badge: "Most Loved",
        features: ["7 shared courses", "2 glasses of vintage champagne", "Window table priority", "Personalized dessert message"],
        featured: true,
        active: true,
      },
      {
        id: "exp-tasting",
        title: "Grand Tasting Menu",
        subtitle: "The Full Lumina Journey",
        description:
          "Nine courses charting a decade of the kitchen's greatest work, with optional sommelier wine pairing drawn from our 600-bottle cellar.",
        price: 195,
        priceLabel: "per guest",
        category: "tasting",
        image: "/images/wagyu.jpg",
        badge: "Chef's Selection",
        features: ["9 courses", "Optional wine pairing (+$120)", "Kitchen tour on request", "Menu keepsake signed by the chef"],
        featured: true,
        active: true,
      },
      {
        id: "exp-jazz",
        title: "Golden Hour Jazz Evenings",
        subtitle: "Live Music · First Friday Monthly",
        description:
          "The lights fall, the quartet begins, and the bar releases a one-night-only cocktail list. Limited to forty guests.",
        price: 85,
        priceLabel: "per guest",
        category: "event",
        image: "/images/negroni.jpg",
        badge: "Limited Seats",
        features: ["Live jazz quartet", "Welcome cocktail", "Late-night bar menu", "First Friday of every month"],
        featured: false,
        active: true,
      },
      {
        id: "exp-private",
        title: "The Private Room",
        subtitle: "Celebrations & Corporate Dinners",
        description:
          "An intimate mirrored salon for eight to eighteen guests with a dedicated captain, bespoke menu and full audiovisual discretion.",
        price: 1500,
        priceLabel: "minimum spend",
        category: "private",
        image: "/images/lobster.jpg",
        features: ["Seats 8–18 guests", "Dedicated captain & sommelier", "Bespoke printed menus", "Private entrance available"],
        featured: false,
        active: true,
      },
    ],
    tables: [
      {
        id: "table-standard",
        name: "Dining Room Table",
        description: "The heart of the room, beneath the amber chandeliers.",
        capacityMin: 1,
        capacityMax: 6,
        minimumSpend: 0,
        perks: ["Full à la carte menu", "Classic Lumina service"],
        active: true,
      },
      {
        id: "table-window",
        name: "Window Table",
        description: "Candlelit tables along the glass wall overlooking the avenue.",
        capacityMin: 2,
        capacityMax: 4,
        minimumSpend: 150,
        perks: ["Skyline view", "Complimentary amuse-bouche", "Priority for couples"],
        active: true,
      },
      {
        id: "table-chefs",
        name: "Chef's Counter",
        description: "Six seats at the pass, inches from the fire and the plating.",
        capacityMin: 1,
        capacityMax: 6,
        minimumSpend: 195,
        perks: ["Front-row kitchen view", "Course narration by the chefs", "Tasting menu only"],
        active: true,
      },
      {
        id: "table-private",
        name: "Private Dining Room",
        description: "A mirrored salon of its own for celebrations and quiet business.",
        capacityMin: 8,
        capacityMax: 18,
        minimumSpend: 1500,
        perks: ["Dedicated captain", "Bespoke menu", "Full privacy"],
        active: true,
      },
    ],
    reservations: [],
    orders: [],
    messages: [],
    analytics: [],
  }
}
